### ISSUE TITLE
Update README.Md  

### ISSUE THREAD

**Issue by Akshit6828** [Akshit6828/Traverse-Indoor#8]
It needs to add some data and check some grammatical mistakes.

**Comment by Amisha328** [comment]
Hello,
Can I solve this issue.

**Comment by Akshit6828** [comment]
@Amisha328  Yes Sure! Please Run the App on your local Machine and Update the README.Md for the visitors to know about the project. Create a separate Branch and let me know when you are done! I will surely consider your PR's.
